---
- name: Create Service Ticket
  hosts: localhost
  gather_facts: no

  vars:
   SN_HOST: 
   SN_USERNAME: 
   SN_PASSWORD:
   description:

  tasks:
   - name: Create Ticket
     servicenow.itsm.incident:
      instance:
       host: "{{ SN_HOST }}"
       username: "{{ SN_USERNAME }}"
       password: "{{ SN_PASSWORD }}"
      state: New
      caller: Admin
      short_description: "{{ description }}"
      impact: low
      urgency: low
     register: ticket_details
     delegate_to: localhost

   - name: print
     debug:
      msg: "{{ ticket_details }}"
