---
- name: Create Service Ticket
  hosts: localhost
  gather_facts: no

  vars:
    ticket_number:
    SN_HOST: 
    SN_USERNAME: 
    SN_PASSWORD:

  tasks:
    - name: Get Ticket Info
      servicenow.itsm.incident_info:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        number: "{{ ticket_number }}"
      register: ticket_details
      delegate_to: localhost

    - name: print
      debug:
        msg: "{{ ticket_details }}"
